development:
  adapter: postgresql
  database: paddlebox_development
  pool: 5
  min_messages: 'warning'
  encoding: utf8

test: &test
  adapter: postgresql
  database: paddlebox_test
  pool: 5
  min_messages: 'warning'
  encoding: utf8
